dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.2
compiler:
  solc:
    version: 0.8.0
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.2'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

networks:
  default: development
  development:
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
